### ISSUE TITLE
Print help message after connecting to the device

### ISSUE THREAD

**Issue by f0086** [yesco/esp-lisp#2]

**Comment by yesco** [comment]
Hi.

Thanks for feedbacks, travelling but will look at it today!

There is no way that I know of how to detect that somebody connects to the
serial port. Currently, when esp-lisp starts up I wait to init till user
presses return. I guess after that/init would be good place to print the
help message.

**Comment by yesco** [comment]
[fix](https://github.com/yesco/esp-lisp/commit/c62acf5c1835a567e3268f5bd6793e449972a9b6)
